# =============================================================================
# Dependabot Configuration
# =============================================================================

version: 2

updates: []
