# 使用官方的 Ubuntu 作为基础镜像
FROM quay.io/qiime2/metagenome:2024.5

CMD ["/bin/bash"]

# apptainer build qiime2_metagenome_v2024.5.sif quay.io/qiime2/metagenome:2024.5

# sudo apptainer build qiime2_core_v2023.9.sif docker://quay.io/qiime2/core:2023.9